In [68]:
import numpy as np
import pandas as pd

In [69]:
from sklearn.datasets import load_iris

In [70]:
iris = load_iris()

In [71]:
type(iris)

sklearn.utils.Bunch

In [72]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [73]:
X = iris.data

In [74]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [75]:
y = iris.target

In [76]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [77]:
# We need some categorical points to work through neural networks

from keras.utils import to_categorical

In [78]:
# We just now have to cast to y data
y = to_categorical(y)

In [79]:
y.shape

(150, 3)

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33)

In [82]:
# For the purpose of neural networks, it is always a good idea to normaize your data
from sklearn.preprocessing import MinMaxScaler

In [83]:
scaler_obj = MinMaxScaler()

In [84]:
scaler_obj.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [85]:
scaled_Xtrain = scaler_obj.transform(X_train)

In [86]:
scaler_obj.fit(X_test)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [87]:
scaled_Xtest = scaler_obj.transform(X_test)

In [88]:
from keras.models import Sequential
from keras.layers import Dense

In [89]:
model = Sequential()
model.add(Dense(8,input_dim = 4, activation='relu'))
model.add(Dense(8,input_dim = 4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [90]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [91]:
model.fit(scaled_Xtrain,y_train, epochs=150,verbose = 2)

Epoch 1/150
 - 1s - loss: 1.1427 - acc: 0.0600
Epoch 2/150
 - 0s - loss: 1.1369 - acc: 0.1500
Epoch 3/150
 - 0s - loss: 1.1318 - acc: 0.2800
Epoch 4/150
 - 0s - loss: 1.1272 - acc: 0.3500
Epoch 5/150
 - 0s - loss: 1.1230 - acc: 0.3500
Epoch 6/150
 - 0s - loss: 1.1189 - acc: 0.3500
Epoch 7/150
 - 0s - loss: 1.1147 - acc: 0.3500
Epoch 8/150
 - 0s - loss: 1.1104 - acc: 0.3500
Epoch 9/150
 - 0s - loss: 1.1063 - acc: 0.3500
Epoch 10/150
 - 0s - loss: 1.1022 - acc: 0.3500
Epoch 11/150
 - 0s - loss: 1.0981 - acc: 0.3500
Epoch 12/150
 - 0s - loss: 1.0943 - acc: 0.3500
Epoch 13/150
 - 0s - loss: 1.0907 - acc: 0.3500
Epoch 14/150
 - 0s - loss: 1.0873 - acc: 0.3500
Epoch 15/150
 - 0s - loss: 1.0838 - acc: 0.3500
Epoch 16/150
 - 0s - loss: 1.0803 - acc: 0.3500
Epoch 17/150
 - 0s - loss: 1.0767 - acc: 0.3500
Epoch 18/150
 - 0s - loss: 1.0733 - acc: 0.3500
Epoch 19/150
 - 0s - loss: 1.0696 - acc: 0.3500
Epoch 20/150
 - 0s - loss: 1.0661 - acc: 0.3500
Epoch 21/150
 - 0s - loss: 1.0622 - acc: 0.3500
E

In [92]:
predictions = model.predict_classes(scaled_Xtest)

In [93]:
y_test.argmax(axis=1)

array([1, 0, 0, 0, 2, 2, 1, 1, 2, 0, 1, 2, 2, 0, 2, 1, 0, 1, 2, 0, 1, 2,
       2, 1, 1, 2, 2, 0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 2, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0], dtype=int64)

In [94]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [95]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0,  2, 14],
       [ 0,  0, 15]], dtype=int64)

In [96]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.12      0.22        16
           2       0.52      1.00      0.68        15

   micro avg       0.72      0.72      0.72        50
   macro avg       0.84      0.71      0.63        50
weighted avg       0.86      0.72      0.66        50



# Text Generation with Keras and LSTM using GRU

In [97]:
# Convinient function to read the files

def file_access(filename):
    with open(filename) as f:
        text = f.read()
        
    return text

In [98]:
#file_access('../UPDATED_NLP_COURSE/06-Deep-Learning/moby_dick_four_chapters.txt') # lot of noise

In [99]:
# spacy to clean and tokenize text

import spacy
nlp = spacy.load('en_core_web_sm')

In [100]:
doc = nlp(file_access('../UPDATED_NLP_COURSE/06-Deep-Learning/moby_dick_four_chapters.txt'))

In [101]:
def text_cleaner(doc_text):
    return [token.text.lower() for token in doc_text if token.text not in '\n\n  \n\n\n!"#$%&\'()*+,-- -./:;<=>?@[\\]^_`{|}~ \t \n']

In [102]:
tokens = text_cleaner(doc)

In [103]:
#tokens

In [104]:
# Now we will create sequences of text from the document which will basically predict the 26th word from the previous 25 words

train_len = 25 + 1

text_seq = []

for i in range(train_len, len(tokens)):
    seq = tokens[i-train_len:i]
    
    text_seq.append(seq)

In [105]:
#text_seq[0]

In [106]:
# Now we need to convert these sequences to numerical tokens for keras to understand

from keras.preprocessing.text import Tokenizer

In [107]:
# Creating a tokenizer object
tokenizer =Tokenizer()

In [108]:
tokenizer.fit_on_texts(text_seq)

In [109]:
sequences = tokenizer.texts_to_sequences(text_seq)

In [110]:
#sequences[0]

In [111]:
# Whenever you want to check the mapping of the tokens to sequences
len(tokenizer.index_word)

2707

In [112]:
# How many times each word appears in the text
len(tokenizer.word_counts)

2707

In [113]:
# since it is better to view it as a numpy array, we can cast it into a nice array

import numpy as np
sequences = np.array(sequences)

In [114]:
sequences

array([[ 962,   14,  264, ..., 2702,   14,   24],
       [  14,  264,   51, ...,   14,   24,  963],
       [ 264,   51,  262, ...,   24,  963,    5],
       ...,
       [ 958,   12,  167, ...,  263,   53,    2],
       [  12,  167, 2701, ...,   53,    2, 2707],
       [ 167, 2701,    3, ...,    2, 2707,   26]])

In [115]:
# Taking all the values except the last one as features values
X = sequences[:,:-1]

In [116]:
# Taking the last value as the y_train
y = sequences[:,-1]

In [117]:
from keras.utils import to_categorical

In [118]:
vocab_size = len(tokenizer.word_counts)

In [119]:
y = to_categorical(y, num_classes =vocab_size +1 )

In [120]:
X.shape

(11351, 25)

In [121]:
# This has been set as 25 for future adjustments
seq_len = X.shape[1]

In [122]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding

In [130]:
def create_model(vocab_size, seq_len):
    
    
    model = Sequential()
    model.add(Embedding(vocab_size, seq_len, input_length=seq_len))
    model.add(LSTM(50, return_sequences=True))
    model.add(LSTM(50))
    model.add(Dense(50, activation='relu'))
    
    model.add(Dense(vocab_size, activation='softmax'))
    
    model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    model.summary()
    
    return model

In [134]:
model = create_model(vocab_size+1, seq_len)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 25, 25)            67700     
_________________________________________________________________
lstm_7 (LSTM)                (None, 25, 50)            15200     
_________________________________________________________________
lstm_8 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense_13 (Dense)             (None, 50)                2550      
_________________________________________________________________
dense_14 (Dense)             (None, 2708)              138108    
Total params: 243,758
Trainable params: 243,758
Non-trainable params: 0
_________________________________________________________________


In [132]:
from pickle import dump, load

In [151]:
model.fit(X,y,batch_size=150, epochs=300, verbose=1)

Epoch 1/300
11351/11351 [==============================] - 23s 2ms/step - loss: 4.5984 - acc: 0.1162
Epoch 2/300
11351/11351 [==============================] - 10s 862us/step - loss: 4.5704 - acc: 0.1179
Epoch 3/300
11351/11351 [==============================] - 10s 911us/step - loss: 4.5420 - acc: 0.12092s - loss: 4.5
Epoch 4/300
11351/11351 [==============================] - 10s 907us/step - loss: 4.5139 - acc: 0.1189
Epoch 5/300
11351/11351 [==============================] - 10s 885us/step - loss: 4.4858 - acc: 0.1233
Epoch 6/300
11351/11351 [==============================] - 11s 981us/step - loss: 4.4597 - acc: 0.1255
Epoch 7/300
11351/11351 [==============================] - 13s 1ms/step - loss: 4.4293 - acc: 0.1262
Epoch 8/300
11351/11351 [==============================] - 11s 964us/step - loss: 4.3958 - acc: 0.1297
Epoch 9/300
11351/11351 [==============================] - 9s 831us/step - loss: 4.3712 - acc: 0.1337
Epoch 10/300
11351/11351 [==============================] - 10s 

11351/11351 [==============================] - 18s 2ms/step - loss: 2.2086 - acc: 0.4584
Epoch 160/300
11351/11351 [==============================] - 18s 2ms/step - loss: 2.2169 - acc: 0.4571
Epoch 161/300
11351/11351 [==============================] - 19s 2ms/step - loss: 2.2192 - acc: 0.4511
Epoch 162/300
11351/11351 [==============================] - 20s 2ms/step - loss: 2.2009 - acc: 0.4583
Epoch 163/300
11351/11351 [==============================] - 18s 2ms/step - loss: 2.1858 - acc: 0.4668
Epoch 164/300
11351/11351 [==============================] - 17s 2ms/step - loss: 2.1858 - acc: 0.4645
Epoch 165/300
11351/11351 [==============================] - 17s 2ms/step - loss: 2.1618 - acc: 0.4737
Epoch 166/300
11351/11351 [==============================] - 17s 2ms/step - loss: 2.1531 - acc: 0.4701
Epoch 167/300
11351/11351 [==============================] - 21s 2ms/step - loss: 2.1516 - acc: 0.4733
Epoch 168/300
11351/11351 [==============================] - ETA: 0s - loss: 2.1371 - a

In [152]:
model.save('my_mobydick_model.h5')

In [153]:
dump(tokenizer, open('my_firsttokenizer', 'wb'))

In [154]:
from keras.preprocessing.sequence import pad_sequences

In [155]:
def generate_text (model, tokenizer, seq_len, seed_text, num_gen_words ):
    
    output_text = []
    input_text = seed_text # starting text for the model for prediction
    
    
    for i in range(num_gen_words):
        
        encoded_text = tokenizer.texts_to_sequences([input_text])[0] #same step we did for converting text to sequences
        
        pad_encoded  = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre') # to incorporate unbalanced text
        
        pred_word_index = model.predict_classes(pad_encoded, verbose=0)[0] # index value of the words from the predicted values
        
        pred_word = tokenizer.index_word[pred_word_index] # actual word from the vocabulary to get the english word
        
        input_text += ' ' + pred_word # finally the text is feeded into 
        
        output_text.append(pred_word) # output text is a list of strings and we join it to make a sentence
        
    return ' '.join(output_text)
    

In [159]:
seed_text = ' '.join(text_seq[3])

In [160]:
seed_text

'some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i thought'

In [161]:
generate_text(model, tokenizer,seq_len, seed_text=seed_text, num_gen_words=25)

"i would sail at their strange inn ashore to myself with the room and somehow and then n't see a word that being bed the"